### ISSUE TITLE
Choosing optimal value for parameter m to reduce memory footprint of graph

### ISSUE THREAD

**Issue by naveenkumarmarri** [opendistro-for-elasticsearch/k-NN#110]
I'm trying to choose an optimal parameter for `m` 
The dimensionality of the vector I'm trying to index is 2048.
In the [doc ](https://github.com/nmslib/hnswlib/blob/master/ALGO_PARAMS.md) of hnswlib, it is suggested that for vectors with high dimensionality, choose value between 48 to 64.  
Since this parameter affects the quality of results. Is there way to get the recall for a query when search is performed on the index using KNN.

**Comment by vamshin** [comment]
Hi @naveenkumarmarri ,

There is no straight forward way to determine optimal ```m```.  You might need to experiment with your data set to figure out the ```m``` that brings you close to the 100% recall(you could determine exact neighbors by running bruteforce knn algorithm and compare).

 hnsw is approximate knn(AKNN) algorithm. Since we do not know the ground truth about the exact neighbors for a given query vector, we cannot determine the recall for your query. If you are concerned about the recall rate and do not want to experiment much, choosing higher value of ```m``` around 100 should work in most of the cases but as you rightly said it comes with memory cost. So you might need to choose the trade off

**Comment by naveenkumarmarri** [comment]
Thanks @vamshin
