### ISSUE TITLE
ef_search and ef_construction parameters missing in cluster settings output

### ISSUE THREAD

**Issue by naveenkumarmarri** [opendistro-for-elasticsearch/k-NN#119]
I tried to create index

```
def create_index(self, index, dimension, m, ef_s, ef_c, knn=True):
        if not self.es.indices.exists(index=index):
            index_settings = {
            "settings": {
                "index": {
                    "knn": True,
                    "knn.algo_param.m": m,
                    "knn.algo_param.ef_search": ef_s,
                    "knn.algo_param.ef_construction": ef_c
                }
            },
            "mappings": {
                "properties": {
                "embeddings": {
                    "type": "knn_vector",
                    "dimension": dimension
                    }
                }
            }
            }
            self.es.indices.create(index = index, body = index_settings)

```
Created the index with the following settings
```
doc.create_index("test", 2048, 200, 1024, 1024)
m: 200
ef_search: 1024
ef_construction:1024
```

When tried to retrieve the settings of the index, I can only see the `m` parameter in the output. `ef_search` and `ef_construction` parameters are not available in the ouput
```
curl https://instance:PORT/test/_settings?pretty
{
  "test" : {
    "settings" : {
      "index" : {
        "algo_param" : {
          "m" : "200"
        },
        "number_of_shards" : "5",
        "provided_name" : "test",
        "knn" : "true",
        "creation_date" : "1589917372582",
        "number_of_replicas" : "1",
        "uuid" : "vK-RGGQQTw-viYmsDtZM-g",
        "version" : {
          "created" : "7010199"
        }
      }
    }
  }
}
```

**Comment by vamshin** [comment]
Hi @naveenkumarmarri ,

this is a bug in ES 7.1 with settings having same prefix. To retrieve knn related settings you can use 

curl https://instance:PORT/test/index.knn.*/_settings?pretty

**Comment by naveenkumarmarri** [comment]
@vamshin 
Thanks for the response. I got the following results when I tried with the command you provided
```
curl https://instance:PORT/test/index.knn.*/_settings?pretty
{
  "_index" : "test",
  "_type" : "index.knn.*",
  "_id" : "_settings",
  "found" : false
}
```

**Comment by vamshin** [comment]
oops sorry my bad. Please find correct query

curl https://instance:PORT/test/_settings/index.knn.*?pretty"

**Comment by naveenkumarmarri** [comment]
thanks that worked

**Comment by naveenkumarmarri** [comment]
@vamshin Also, how does the increase in `ef_search` parameter affect the latency. I did few experiments by adding 1M 2048 dimension docs to ES index and increased the from 512 to 1024. I didn't see significant latency increase.

**Comment by jmazanec15** [comment]
From NMSLIB's [documentation](https://github.com/nmslib/nmslib/blob/master/manual/methods.md), ef_search increases the retrieval time. ef_search is a parameter that impacts the number of candidates considered during the search of each layer in the HNSW graph. The more candidates considered, the longer the search will take. Their [paper](https://arxiv.org/abs/1603.09320) has more details on how it factors into the search process.

@naveenkumarmarri  How many segments does your index have? Because each ES segment maps to an HNSW graph, each graph size could be small enough where this change does not make a major impact, and latency could be dominated by Elasticsearch operations.

**Comment by naveenkumarmarri** [comment]
@jmazanec15 there is ~400 segments for 1M docs indexed.

- Do you suggest to merge the segments, to get better latency?

- Also, does merging the segments improve the quality(recall) of the results.

**Comment by vamshin** [comment]
@naveenkumarmarri 

>>**Do you suggest to merge the segments, to get better latency?**

Graphs are queried sequentially inside a shard.  Having merge to 1 segment will give you optimal performance. To avoid single segment containing a huge graph, you could break down to multiple shards and forcemerge. Note, forcemerge is a costly operation and should be considered during low load on cluster.

Force merge call to have single segment below
```
POST /<index_name>/_forcemerge?max_num_segments=1
```

>> **Also, does merging the segments improve the quality(recall) of the results.**

Merging segments can impact recall because we will be now running with same algo params on a larger graph. But if you already chosen large enough algo params recall might still be intact.
You might want to experiment with your data set to see what algo params works better.

Also on the side note, following recommendations can improve search performance
*graphs are loaded to memory only when you search and cached later on. So initial queries could take time. So you might want to run queries for warm up, may be couple of minutes. We have plan to expose warmup api to make it easy.

- Avoid loading all the stored fields
If you are just trying out vector search(all you need is the nearest doc ids for the query vector), you can improve the performance by asking Elasticsearch not to read the stored fields.
```
Example;-
{
"size": 5,
"stored_fields": "_none_",
"docvalue_fields": ["_id"],
"query": {
  "knn": {
   "v": {            
     "vector": [-0.16490704,-0.047262248,-0.078923926],
     "k": 50
   }       
  }
}
}
```


*You might find this link useful for indexing/search tuning https://medium.com/@kumon/how-to-realize-similarity-search-with-elasticsearch-3dd5641b9adb

**Comment by naveenkumarmarri** [comment]
@vamshin does the value of `graph_memory_usage` depend on the number of replicas set in the index.
I've cluster with number of replicas set to 1. I see the `graph_memory_usage` twice compared to the value obtained from the formula `4 * D + 8 * M` bytes
