### ISSUE TITLE
Use containers for library artifact build

### ISSUE THREAD

**Issue by jmazanec15** [opendistro-for-elasticsearch/k-NN#169]
We should use containers for the library build and release in our Github Action to control the environment better. 

Additionally, for the DEB artifact, we should continue to use Ubuntu 16.04. But for RPM, we should use Centos 7 as opposed to Ubuntu.

**Comment by peterzhuamazon** [comment]
As we discussed @jmazanec15 since CentOS have the lowest version of glibc, it would make sense to compile all distros of knnlib (zip/deb/rpm) in CentOS.

On Debian Stretch (9):
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24

On CentOS 7:
ldd (GNU libc) 2.17

On a side note, Debian Jessie (8) is out of the LTS since June 2020, so we are not supporting it anymore.
https://wiki.debian.org/LTS
